language: python
python:
  - "3.3"
  - "3.2"
  - "2.7"
  - "2.6"
install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install unittest2; fi
  - pip install nose
script:  python setup.py test